dynamic: install


all: install


install:
	cp -f libwlbcmcrypto.so_96818O_save $(INSTALL_DIR)/lib/libwlbcmcrypto.so
	cp -f libwlbcmshared.so_96818O_save $(INSTALL_DIR)/lib/libwlbcmshared.so
	cp -f nvram_params_96818O_save $(INSTALL_DIR)/etc/wlan/nvram_params
	cp -f libwlmngr.so_96818O_save $(INSTALL_DIR)/lib/libwlmngr.so
